nelmio_api_doc:
    documentation:
        info:
            title: Swagger para probar los EP
            description: API carrito y checkout
                            Existen 3 Ids de carritos  <br><br>
                                98e93f34-7cce-4fb5-bff8-1e3ac545dff1<br>
                                6222b469-a0e6-4b3d-9a30-5e2b809b9d42<br>
                                d2311b83-02ce-4ca5-9953-587616578aaf<br>
                            <br>
                            Existen 8 productos<br><br> 
                                41a562c5-f282-4c05-a01f-4602509f55c7  - Portátil i7<br>
                                f9a29718-4a09-452c-a716-e963a11f8373  - Ratón Wireless<br>
                                d9dc380c-6712-4f03-86e9-f43f58a57a9d  - Teclado<br>
                                04d48c5a-00e5-4bb1-9997-df3062459b8f  - Monitor 4K<br>
                                7c3d1c10-3d7f-42ee-a15b-30897cf640c2  - Auriculares Gaming<br>
                                ddcd8834-de1e-401e-9829-8c0fe2e81616  - Webcam HD<br>
                                ceae91d9-bf87-4d5f-b57e-eb4b77218546  - Disco duro SSD 1TB<br>
                                9d8e35be-a21c-4a2a-9817-8811a09506ab  - Memoria RAM 16GB<br>
            version: 1.0.0
    areas: # Para documentar solo rutas específicas
        path_patterns:
            - ^/api(?!/doc$) # documenta /api/* excepto /api/doc